# Generated by Django 5.0.6 on 2025-05-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='body',
            field=models.TextField(default=''),
        ),
    ]
